version: 3

tasks:
  install:venv:
  - pip install --user virtualenv

  install:pip:
  - sudo apt install python3-pip -y

  install:requirements:
  - pip install -r requirements.txt

  start:
  - python3 api.py

  venv:
  - virtualenv -p python3 venv

  build:
  - docker build . --tag pav:0.0.1

  start:container:
  - docker run --rm --name pav -p 5000:5000 pav:0.0.1 

  tilt:up:
  - tilt up

  k3d:create:
  - k3d cluster create pav --registry-create registry.localhost:127.0.0.1:5000
  # create registry will be called k3d-registry.localhost
  # it is possible to create registry separately - k3d registry create myregistry.localhost --port 12345
  # and then k3d cluster create newcluster --registry-use k3d-myregistry.localhost:12345 

  k3d:delete:
  - k3d cluster delete pav

# source .env