resources:
    requests:
        cpu: 10m
        memory: 32Mi
webhook:
    resources:
        requests:
            cpu: 10m
            memory: 32Mi
cainjector:
    resources:
        requests:
            cpu: 10m
            memory: 32Mi
startupapicheck:
    resources:
        requests:
            cpu: 10m
            memory: 32Mi
installCRDs: true