apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o autok3s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: autok3s
  name: autok3s
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: autok3s
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o autok3s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: autok3s
    spec:
      containers:
        - env:
            - name: AUTOK3S_CONFIG
              value: /home/krzwiatrzyk/.autok3s/
            - name: VIRTUAL_HOST
              value: autok3s.vcap.me
          image: cnrancher/autok3s:v0.5.0
          name: autok3s
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /tmp/docker.sock
              name: autok3s-claim0
              readOnly: true
            - mountPath: /home/krzwiatrzyk/.autok3s/
              name: autok3s-claim1
      restartPolicy: Always
      volumes:
        - name: autok3s-claim0
          persistentVolumeClaim:
            claimName: autok3s-claim0
            readOnly: true
        - name: autok3s-claim1
          persistentVolumeClaim:
            claimName: autok3s-claim1
status: {}
