apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: kube-prometheus-stack
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`prometheus.{suffix:.*}`)
    kind: Rule
    services:   
    - kind: Service 
      name: kube-prometheus-stack-prometheus
      port: 9090