version: 3

tasks:
  install:helm-git-plugin:
    cmds:
    - helm plugin install https://github.com/aslafy-z/helm-git --version 0.10.0
    status:
    - helm plugin list | grep git
    preconditions:
    - helm

  install:add-repo:
    deps:
    - install:helm-git-plugin
    cmds:
    - helm repo add skydive git+https://github.com/skydive-project/skydive@contrib/charts
    - helm repo update
    status:
    - helm repo list | grep skydive

  install:
    deps:
    - install:add-repo
    cmds:
    - helm upgrade --install skydive-analyzer skydive/skydive-analyzer -n skydive --create-namespace -f analyzer-values.yaml
    - helm upgrade --install skydive-agent skydive/skydive-agent -n skydive --create-namespace 
    - task: install:ingress-route

  install:ingress-route:
    cmds:
    - kubectl apply -f manifests/ingress-route.yaml

  uninstall:
    - helm uninstall -n skydive skydive-agent skydive-analyzer