
version: '3'

tasks:
  install:helm:add-repo:
    cmds:
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    status:
    - helm repo list | grep prometheus
    
  install:helm:
    desc: Install Kube Prometheus Stack
    deps:
    - install:helm:add-repo
    cmds:
    - helm upgrade --install -n kube-prometheus-stack --create-namespace kube-prometheus-stack prometheus-community/kube-prometheus-stack --values values/values.yaml

  install:grafana:ingress-route:
    cmds:
    - kubectl apply -f manifests/grafana-ingress-route.yaml

  install:prometheus:ingress-route:
    cmds:
    - kubectl apply -f manifests/prometheus-ingress-route.yaml