version: 3

tasks:
  install:cli:
    cmds:
    - curl -Lo mizu github.com/up9inc/mizu/releases/latest/download/mizu_linux_amd64 && chmod 755 mizu && sudo mv mizu /usr/local/bin
    status:
    - command -v mizu

  tap:all-namespaces:
  - mizu tap -A