apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consul
  namespace: consul
spec:
  rules:
  - host: consul.127.0.0.1.nip.io
    http:
      paths:
      - backend:
          service:
            name: consul-ui
            port:
              name: http
        path: /
        pathType: Prefix