apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: heimdall
  namespace: heimdall
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`heimdall.{ip:.*}.nip.io`)
    kind: Rule
    services:   
    - kind: Service 
      name: heimdall
      port: 80