version: 3

tasks:
  install:cli:
    desc: Install telepresence
    cmds:
    - sudo curl -fL https://app.getambassador.io/download/tel2/linux/amd64/latest/telepresence -o /usr/local/bin/telepresence
    - sudo chmod a+x /usr/local/bin/telepresence
    status:
    - command -v telepresence

  connect:
    deps:
    - install:cli
    cmds:
    - telepresence connect