apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${DOMAIN}
  namespace: cert-manager
spec:
  secretName: ${DOMAIN}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ${DOMAIN}
  dnsNames:
  - ${DOMAIN}