version: 3

tasks:
  install:operator:
  - kubectl apply -f https://github.com/knative/operator/releases/download/knative-v1.4.0/operator.yaml

  install:serving:
  - kubectl apply -f manifests/knative-serving.yaml

  install:cli:
    vars:
      VERSION: 1.4.0
    cmds:
      - wget https://github.com/knative/client/releases/download/knative-v{{ .VERSION }}/kn-linux-amd64
      - chmod +x kn-linux-amd64
      - sudo mv kn-linux-amd64 /usr/local/bin/kn

  demo:service:hello:
  - >
    kn service create hello
    --image gcr.io/knative-samples/helloworld-go
    --port 8080
    --env TARGET=World
    --revision-name=world
