version: 3

tasks:
  create:tlsstore:
    env:
      DOMAIN: '{{ .DOMAIN }}'
    cmds:
    - envsubst < manifests/acme-tlsstore.yaml | kubectl apply -f -
    
  install:ingress-route:
    cmds:
    - kubectl apply -f manifests/ingress-route.yaml
