version: 3

tasks:
  install:cli:
    cmds:
    - arkage get argocd
    status:
    - command -v argocd

  install:cli:autocompletion:
    cmds:
    - argocd completion zsh > "${HOME}/.oh-my-zsh/custom/plugins/fzf-zsh-plugin/completions/_argocd"
    - compinit
    #- argocd completion zsh > ~/.oh-my-zsh/custom/argocd.zsh
    

  install:helm:add-repo:
    cmds:
    - helm repo add argo https://argoproj.github.io/argo-helm
    status:
    - helm repo list | grep argo 

  install:helm:
  - helm upgrade --install argocd argo/argo-cd -n argocd --create-namespace -f values/argocd.yaml
  
  install:ingress-route:
  - kubectl apply -f manifests/ingress-route.yaml

  create-key-secret:
    cmds:
    - kubectl create secret generic -n argocd helm-secrets-private-keys --from-file=key.asc=${HOME}/.age
    status:
    - kubectl get -n argocd secret helm-secrets-private-keys